<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Shrooms.Domain.Exceptions</AssemblyTitle>
    <Product>Shrooms.Domain.Exceptions</Product>
  </PropertyGroup>

</Project>