// <auto-generated />
namespace Shrooms.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KnowYourSpeaker_Logs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KnowYourSpeaker_Logs));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151443599_KnowYourSpeaker_AnswersLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
