<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>Shrooms.EmailTemplates.Seeds</AssemblyTitle>
    <Product>Shrooms.EmailTemplates.Seeds</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.Contracts\Shrooms.Contracts.csproj" />
    <ProjectReference Include="..\Shrooms.Premium\Shrooms.Premium.csproj" />
  </ItemGroup>

</Project>
