<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>Shrooms.Contracts</AssemblyTitle>
    <Product>Shrooms.Contracts</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="MimeKit" Version="4.8.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
    <PackageReference Include="X.PagedList" Version="10.5.9" />
  </ItemGroup>

</Project>
