<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>Shrooms.Contracts</AssemblyTitle>
    <Product>Shrooms.Contracts</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="X.PagedList" />
  </ItemGroup>

</Project>
