<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>Shrooms.Domain</AssemblyTitle>
    <Product>Shrooms.Domain</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="CommonMark.NET" Version="0.15.1" />
    <PackageReference Include="EPPlus" Version="7.5.3" />
    <PackageReference Include="HtmlSanitizer" Version="9.0.873" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="MoreLinq" Version="4.4.0" />
    <PackageReference Include="X.PagedList" Version="10.5.9" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="9.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.Authentification\Shrooms.Authentification.csproj" />
    <ProjectReference Include="..\Shrooms.Infrastructure\Shrooms.Infrastructure.csproj" />
    <ProjectReference Include="..\Shrooms.Domain.ServiceValidators\Shrooms.Domain.ServiceValidators.csproj" />
  </ItemGroup>
</Project>
