<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>Shrooms.Domain</AssemblyTitle>
    <Product>Shrooms.Domain</Product>
  </PropertyGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="MoreLinq" />
    <PackageReference Include="X.PagedList" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.Authentification\Shrooms.Authentification.csproj" />
    <ProjectReference Include="..\Shrooms.Infrastructure\Shrooms.Infrastructure.csproj" />
    <ProjectReference Include="..\Shrooms.Domain.ServiceValidators\Shrooms.Domain.ServiceValidators.csproj" />
  </ItemGroup>
</Project>
