<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Shrooms.Domain.ServiceValidators</AssemblyTitle>
    <Product>Shrooms.Domain.ServiceValidators</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.Resources\Shrooms.Resources.csproj" />
    <ProjectReference Include="..\Shrooms.DataLayer.EntityModels\Shrooms.DataLayer.EntityModels.csproj" />
    <ProjectReference Include="..\Shrooms.Contracts.DataTransferObjects\Shrooms.Contracts.DataTransferObjects.csproj" />
    <ProjectReference Include="..\Shrooms.Domain.Exceptions\Shrooms.Domain.Exceptions.csproj" />
    <ProjectReference Include="..\Shrooms.Contracts\Shrooms.Contracts.csproj" />
  </ItemGroup>
</Project>
