<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>Shrooms.Authentification</AssemblyTitle>
    <Product>Shrooms.Authentification</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.DataLayer\Shrooms.DataLayer.csproj" />
    <ProjectReference Include="..\Shrooms.Resources\Shrooms.Resources.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Membership\ShroomsSignInManager.cs" />
  </ItemGroup>
</Project>
