//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.Events {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.Events.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        internal static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Events.
        /// </summary>
        internal static string EntityNamePlural {
            get {
                return ResourceManager.GetString("EntityNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need additional select for this task?.
        /// </summary>
        internal static string EventAdditionalSelect {
            get {
                return ResourceManager.GetString("EventAdditionalSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EventCancel {
            get {
                return ResourceManager.GetString("EventCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description.
        /// </summary>
        internal static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string EventEveryDay {
            get {
                return ResourceManager.GetString("EventEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        internal static string EventEveryMonth {
            get {
                return ResourceManager.GetString("EventEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        internal static string EventEveryWeek {
            get {
                return ResourceManager.GetString("EventEveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event master.
        /// </summary>
        internal static string EventMaster {
            get {
                return ResourceManager.GetString("EventMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max team members.
        /// </summary>
        internal static string EventMaxMembers {
            get {
                return ResourceManager.GetString("EventMaxMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one more.
        /// </summary>
        internal static string EventMore {
            get {
                return ResourceManager.GetString("EventMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        internal static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string EventNo {
            get {
                return ResourceManager.GetString("EventNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of event.
        /// </summary>
        internal static string EventPhoto {
            get {
                return ResourceManager.GetString("EventPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of event.
        /// </summary>
        internal static string EventPlace {
            get {
                return ResourceManager.GetString("EventPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it recurring event?.
        /// </summary>
        internal static string EventRecurring {
            get {
                return ResourceManager.GetString("EventRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EventSave {
            get {
                return ResourceManager.GetString("EventSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time.
        /// </summary>
        internal static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string EventYes {
            get {
                return ResourceManager.GetString("EventYes", resourceCulture);
            }
        }
    }
}
