<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <AssemblyTitle>Shrooms.EmailTemplates</AssemblyTitle>
    <Product>Shrooms.EmailTemplates</Product>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.Contracts\Shrooms.Contracts.csproj" />
    <ProjectReference Include="..\Shrooms.Domain\Shrooms.Domain.csproj" />
  </ItemGroup>

</Project>
