<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>Shrooms.Presentation.WebViewModels</AssemblyTitle>
    <Product>Shrooms.Presentation.WebViewModels</Product>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DataAnnotationsExtensions" Version="5.0.1.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shrooms.Resources\Shrooms.Resources.csproj" />
    <ProjectReference Include="..\Shrooms.DataLayer.EntityModels\Shrooms.DataLayer.EntityModels.csproj" />
  </ItemGroup>
</Project>
