using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Shrooms.DataLayer.EFCoreMigrations
{
    /// <summary>
    /// The public holiday calendar, and the leave already booked against it.
    ///
    /// The seed is generated by build/Generate-HolidaySeed.ps1 from calendar.lt and
    /// pasted here rather than fetched at deploy time, so applying this migration
    /// never depends on that service being reachable. Every insert is guarded, so
    /// the migration is safe on a database that already has some of these rows.
    /// </summary>
    public partial class AddHolidays : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Holidays",
                columns: table => new
                {
                    Date = table.Column<DateTime>(type: "date", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Holidays", x => x.Date);
                });

            migrationBuilder.Sql(@"-- Generated by build/Generate-HolidaySeed.ps1 from calendar.lt for 2026-2040.
-- Do not hand-edit: regenerate instead.
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-04-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-04-06', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2026-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2026-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-03-29')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-03-29', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2027-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2027-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-04-17')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-04-17', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2028-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2028-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-04-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-04-02', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2029-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2029-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-04-22')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-04-22', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2030-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2030-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-04-14')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-04-14', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2031-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2031-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-03-29')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-03-29', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2032-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2032-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-04-18')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-04-18', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2033-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2033-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-04-10')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-04-10', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2034-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2034-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-03-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-03-26', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2035-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2035-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-04-14')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-04-14', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2036-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2036-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-04-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-04-06', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2037-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2037-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-01-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-01-01', N'Naujųjų metų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-04-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-04-26', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2038-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2038-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-03-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-03-11', N'Lietuvos Nepriklausomybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-04-11')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-04-11', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-06-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-06-24', N'Rasos ir Joninių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2039-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2039-12-26', N'Antroji Šventųjų Kalėdų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-02-16')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-02-16', N'Lietuvos valstybės atkūrimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-04-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-04-02', N'Antroji Velykų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-05-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-05-01', N'Tarptautinė darbo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-07-06')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-07-06', N'Mindaugo karūnavimo diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-08-15')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-08-15', N'Žolinė, Šv. Mergelės Marijos ėmimo į dangų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-11-01')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-11-01', N'Visų šventųjų diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-11-02')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-11-02', N'Mirusiųjų atminimo (Vėlinių) diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-12-24')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-12-24', N'Kūčių diena');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-12-25')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-12-25', N'Šventosios Kalėdos (Šv. Kūdikėlio Jėzaus gimimas)');
IF NOT EXISTS (SELECT 1 FROM dbo.Holidays WHERE [Date] = '2040-12-26')
    INSERT INTO dbo.Holidays ([Date], [Name]) VALUES ('2040-12-26', N'Antroji Šventųjų Kalėdų diena');
");

            // Working days used to exclude weekends only, so every stored count is
            // too high by the holidays inside its period. Subtracting is exact:
            // the existing figure is a correct weekends-only count, and the rows
            // being removed are by definition inside the range.
            //
            // Only requests that have not finished yet. A request already settled
            // was paid against the figure it carries, and restating it now would
            // silently disagree with a payslip that has already gone out.
            //
            // The weekend test is DATEDIFF-based rather than DATEPART(weekday):
            // 1900-01-01 was a Monday, so 5 and 6 are Saturday and Sunday whatever
            // the connection's DATEFIRST happens to be. A holiday falling at the
            // weekend was never counted, so it must not be subtracted.
            migrationBuilder.Sql(@"
UPDATE r
SET r.WorkingDays = r.WorkingDays - (
        SELECT COUNT(*)
        FROM dbo.Holidays h
        WHERE h.[Date] >= CAST(r.DateFrom AS date)
          AND h.[Date] <= CAST(r.DateTo AS date)
          AND (DATEDIFF(day, '19000101', h.[Date]) % 7) NOT IN (5, 6))
FROM dbo.VacationRequests r
WHERE r.DateTo >= CAST(GETUTCDATE() AS date)
");
        }

        /// <summary>
        /// Deliberately does not restore the old WorkingDays figures. Reversing the
        /// arithmetic needs the holiday rows, and dropping them is what this method
        /// does — so a rollback leaves future requests short by their holidays.
        /// Recorded rather than solved: it is a one-way migration in practice.
        /// </summary>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Holidays");
        }
    }
}